name: Deploy to Render

on:
  push:
    branches:
      - sm4
      - main
  workflow_dispatch: # Enables manual "Run workflow" button in GitHub Actions tab

jobs:
  trigger-render:
    name: Call Render Deploy Hook
    runs-on: ubuntu-latest

    steps:
      - name: Send POST Request to Render
        run: curl -fsS -X POST "$DEPLOY_HOOK"
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
